#!/usr/bin/env python3
# Template auto-generated by polygraphy [v0.49.0] on 02/16/24 at 10:40:10
# Generation Command: /home/orin/garuda_env/bin/polygraphy run generated/trt/fp16-cifar100-DenseNet201-1.engine --trt --warm-up 10 --iters 2500 --gen polyrun.py
# This script runs /home/orin/GarudaACE/generated/trt/fp16-cifar100-DenseNet201-1.engine using TensorRT.

from polygraphy.logger import G_LOGGER

from polygraphy.backend.common import BytesFromPath
from polygraphy.backend.trt import EngineFromBytes, TrtRunner
from polygraphy.comparator import Comparator, DataLoader
from polygraphy.exception import PolygraphyException

# Data Loader
data_loader = DataLoader(iterations=2500)

# Loaders
load_engine_bytes = BytesFromPath('/home/orin/GarudaACE/generated/trt/fp16-cifar100-DenseNet201-1.engine')
deserialize_engine = EngineFromBytes(load_engine_bytes)

# Runners
runners = [
    TrtRunner(deserialize_engine),
]

# Runner Execution
results = Comparator.run(runners, warm_up=10, data_loader=data_loader)

success = True

# Report Results
if not success:
    raise PolygraphyException('FAILED')
